# Generated by Django 4.1.7 on 2023-02-19 11:41

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_cardobject_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(blank=True, max_length=200, null=True)),
                ("name_ru", models.CharField(blank=True, max_length=200, null=True)),
                ("name_en", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "description_uz",
                    models.TextField(blank=True, max_length=2000, null=True),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, max_length=2000, null=True),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, max_length=2000, null=True),
                ),
                ("icon", models.ImageField(null=True, upload_to="")),
                ("image1", models.ImageField(blank=True, null=True, upload_to="")),
                ("image2", models.ImageField(blank=True, null=True, upload_to="")),
                ("image3", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="store.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=smart_selects.db_fields.GroupedForeignKey(
                group_field="category",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.subcategory",
            ),
        ),
    ]
