# Generated by Django 4.1.7 on 2023-02-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Filial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=100)),
                ("name_ru", models.CharField(blank=True, max_length=100, null=True)),
                ("name_en", models.CharField(blank=True, max_length=100, null=True)),
                ("longitude", models.CharField(blank=True, max_length=100, null=True)),
                ("latitude", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
